debits/urls.py
from django.urls import path
from .views import *
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .prints import *

app_name = 'debits'
urlpatterns = [
    path('agentofclient/', ListAgentOfClient.as_view(), name='agentofclient'),
    path('agentofclient/add/', AgentOfClientAddView.as_view(), name='agentofclient_add'),
    path('agentofclient/edit/<int:pk>', AgentOfClientEditView.as_view(), name='agentofclient_edit'),
    path('agentofclient/delete/<int:pk>', deleteAgentOfClient, name='agentofclient_delete'),

    path('coming/', ListIncomes.as_view(), name='list_income'),
    path('coming/<int:pk>', IncomeId.as_view(), name='income_id'),
    path('coming2/<int:pk>', IncomeId2.as_view(), name='income2_id'),
    path('coming/print/<int:pk>', incomePrint, name='income_print'),
    path('coming/print2/<int:pk>', incomePrint2, name='income_print2'),

    path('coming/add', IncomeDebitsAdd.as_view(), name='income_add'),
    path('coming/edit/<int:pk>', IncomeDebitsEdit.as_view(), name='income_edit'),

    path('clients/', selectAgent, name='clients_jx'),
    path('routes/', selectClient, name='routes_jx'),
    path('debit/', getClientDebits, name='debits_jx'),

    path('report/', ReportView.as_view(), name='report'),
    path('report/client', showReportClientModal, name='report_client_jx'),

    path('clientReport/', ClientReportView.as_view(), name='clientReport'),
    path('clientReport/weight', ClientReportTonnageView.as_view(), name='clientReport_tonnage'),
    path('route/', getRoute, name='routeCR_jx'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

financial/urls.py
from django.urls import path
from .views import *
from .prints import *
from .search import *
from .salary import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'financial'
urlpatterns = [
    path('cash_box/', CashBoxView.as_view(), name='cash_box'),
    path('cash_box/print', printCashBoxes, name='cash_box_print'),
    path('cash_box_add/', CashBoxAddView.as_view(), name='cash_box_add'),

    path('reports/', Reports.as_view(), name='reports'),
    path('get_article/', getArticle, name='reports_article_js'),

    path('articles/', ArticlesView.as_view(), name='articles'),
    path('article/add/', ArticlesViewAdd.as_view(), name='article_add'),
    path('article/edit/<int:pk>/', ArticlesEditView.as_view(), name='article_edit'),
    path('article/delete/<int:id>/', article_delete, name='article_delete'),

    path('operations/', OperationsView.as_view(), name='operations'),

    path('operations/income/view/<int:pk>/', IncomeId.as_view(), name='operations_income_ID'),
    path('operations/consumption/view/<int:pk>', ConsumptionId.as_view(), name='operations_cons_ID'),
    path('operations/payroll/view/<int:pk>', PayrollID.as_view(), name='operations_payroll_ID'),
    path('operations/income/print/<int:pk>', IncomePrint.as_view(), name='operations_income_print'),

    path('operations/delete/<int:pk>', deleteOperations, name='operations_delete'),

    path('operations/income/client/add/', OperationsIncomeClientAdd.as_view(), name='operations_in_client_add'),
    path('operations/income/client/edit/<int:pk>/', OperationsIncomeClientEdit.as_view(), name='operations_in_client_edit'),

    path('operations/income/counterparty/add/', OperationsIncomeAgentAdd.as_view(), name='operations_in_agent_add'),
    path('operations/income/counterparty/edit/<int:pk>/', OperationsIncomeAgentEdit.as_view(), name='operations_in_agent_edit'),

    path('operations/income/various/add/', OperationsVarioustAdd.as_view(), name='operations_in_various_add'),
    path('operations/income/various/edit/<int:pk>', OperationsIncomeVariousEdit.as_view(), name='operations_in_various_edit'),

    path('operations/consumption/employee/add/', ConsumptionEmployeeAdd.as_view(), name='cons_employee_add'),
    path('operations/consumption/employee/edit/<int:pk>', ConsEmployeeEdit.as_view(), name='cons_employee_edit'),
    path('operations/consumption/employee/print/<int:pk>', consEmployee_print, name='cons_employee_print'),

    path('operations/consumption/agent/add/', ConsumptionAgentAdd.as_view(), name='cons_agent_add'),
    path('operations/consumption/agent/edit/<int:pk>', ConsumptionAgentEdit.as_view(), name='cons_agent_edit'),
    path('operations/consumption/agent/print/<int:pk>', consAgent_print, name='cons_agent_print'),

    path('operations/consumption/agent_of_client/', ConsAgentClientAdd.as_view(), name='cons_agent_client_add'),
    path('operations/consumption/agent_of_client/edit/<int:pk>', ConsAgentClientEdit.as_view(), name='cons_agent_client_edit'),
    path('operations/consumption/agent_of_client/print/<int:pk>', consAgentClient_print, name='cons_agent_client_print'),

    path('operations/consumption/various/', OperationsConsVarioustAdd.as_view(), name='cons_various_add'),
    path('operations/consumption/various/edit/<int:pk>', OperationsConsVarioustEdit.as_view(), name='cons_various_edit'),
    path('operations/consumption/various/print/<int:pk>', consVarious_print, name='cons_various_print'),

    path('operations/payroll/emp/add/', PaymentStatementEmployeeAddView.as_view(), name='payroll_emp_add'),
    path('operations/payroll/emp/edit/<int:pk>', PaymentStatementEmployeeEditView.as_view(), name='ps_emp_edit'),
    path('operations/payroll/emp/print/<int:pk>', psEmployee_print, name='ps_emp_print'),

    path('operations/payroll/agent/add/', PaymentStatementAgentAddView.as_view(), name='payroll_agent_add'),
    path('operations/payroll/agent/edit/<int:pk>', PaymentStatementAgentEditView.as_view(), name='ps_agent_edit'),
    path('operations/payroll/agent/print/<int:pk>', psAgent_print, name='ps_agent_print'),

    path('operations/consumption/cash_moving/', OperationsConsCashMovingAdd.as_view(), name='cons_cash_moving_add'),
    path('operations/consumption/cash_moving/<int:pk>', OperationsConsCashMovingID.as_view(),
         name='cons_cash_moving_ID'),
    path('operations/consumption/cash_moving/edit/<int:pk>', OperationsConsCashMovingEdit.as_view(),
         name='cons_cash_moving_edit'),
    path('operations/consumption/cash_moving/print/<int:pk>', consCashMoving_print, name='cons_cash_moving_print'),

    path('advance/', AdvanceView.as_view(), name='prepaid'),
    path('fines', FinesView.as_view(), name='fines'),

    path('work_pay', WorkPayView.as_view(), name='work_pay'),
    path('work_pay/emp/<int:pk>', WorkPayEmpView.as_view(), name='work_pay_emp'),

    path('loading_pay', LoadingPayView.as_view(), name='loading_pay'),
    path('loading_pay/emp/<int:pk>', LoadingPayEmpView.as_view(), name='loading_pay_emp'),

    path('salary', SalaryView.as_view(), name='salary'),
    path('salaryID/<int:pk>', SalaryViewID.as_view(), name='salary_id'),
    path('printsalary/<int:pk>', printSalaryID, name='salary_print'),
    path('salary/add/', SalaryAddView.as_view(), name='salary_add'),
    path('salary/edit/<int:pk>', SalaryEditView.as_view(), name='salary_edit'),
    path('salary/delete/<int:pk>', deleteSalary, name='salary_delete'),

    path('salary/emp/', showEmployeeModal, name='salary_show_emp_jx'),
    path('salary/emp_edit/', showEmployeeEditModal, name='salary_show_emp_edit_jx'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'main'

urlpatterns = [
    path('', views.HomePage.as_view(), name='home_page'),
    path('products', views.Products.as_view(), name='products'),
    path('product/edit/<int:pk>', ProductEditView.as_view(), name='product_edit'),
    path('product/delete/<int:pk>', deleteProduct, name='delete_product'),
    path('product/add/', views.ProductAddView.as_view(), name='product_add'),

    path('clients', views.ClientListView.as_view(), name='clients'),
    path('client/add/', views.ClientAddView.as_view(), name='client_add'),
    path('client/edit/<int:pk>', ClientEditView.as_view(), name='client_edit'),
    path('clients/delete/<int:pk>', delete_client, name='delete_client'),

    #path('senders', SenderListView.as_view(), name='senders'),
    path('senders/addjx/', add_sender, name='sender_add_ajax'),
    path('load_senders/', load_senders, name='load_senders_ajax'),
    path('senders/edit/<int:pk>', SenderEditView.as_view(), name='sender_edit'),
    #path('senders/delete/<int:pk>', delete_sender, name='delete_sender'),

    path('employees', EmployeeListView.as_view(), name='employees'),
    path('employee/add', EmployeeAdd.as_view(), name='employee_add'),
    path('employees/edit/<int:pk>', EmployeeEditView.as_view(), name='employee_edit'),
    path('delete/employees/<int:pk>', delete_employee, name='delete_employee'),

    path('contrageny', AgentOfClients.as_view(), name='contrageny'),
    path('contrageny/add', AgentOfClientAddView.as_view(), name='contrageny_add'),
    path('contrageny/edit/<int:pk>', AgentOfClientEditView.as_view(), name='contragenty_edit'),
    path('contrageny/delete/<int:pk>', delete_agenty, name='delete_contragenty'),

]

route/urls.py
from django.urls import path
from .views import *
from .viewRecTran import *
from .print import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'route'
urlpatterns = [
    path('list/', ListRoute.as_view(), name='list_route_url'),
    path('route/add/', CreateRoute.as_view(), name='create_route_url'),
    path('routeIDD/', showRouteModal, name='show_routeRT_url'),
    path('route/update/<int:pk>/', UpdateRouteView.as_view(), name='update_route_url'),
    path('route/delete/<int:pk>/', deleteRoute, name='delete_route_url'),

    path('routeID/<int:pk>/', ShowRouteID.as_view(), name='show_route_ID_url'),
    path('routeID_bag_report_old/<int:pk>/', RouteBagReportOld.as_view(), name='route_bag_report_old'),
    path('routeID_bag_report/<int:pk>/', RouteBagReportView.as_view(), name='route_bag_report'),
    path('routeID_num_places/<int:pk>/', RouteNumberOfPlaces.as_view(), name='route_num_places'),
    path('routeID_num_places_client/<int:pk>/', RouteNumberOfPlacesClient.as_view(), name='route_num_places_client'),
    path('routeID_num_place_agent/<int:pk>/', RouteNumberOfPlacesAgent.as_view(), name='route_num_places_agent'),
    path('routeID_count_prod/<int:pk>/', RouteCountProducts.as_view(), name='route_count_products'),

    path('routeIDprint/<int:pk>/', printRouteID, name='print_routeID_url'),
    path('routebagReportOldprint/<int:pk>/', printRouteBagReportOld, name='print_bagReport_old'),
    path('routebagReportprint/<int:pk>/', printRouteBagReport, name='print_bagReport'),
    path('routeNumberOfPlacesprint/<int:pk>/', printRouteNumberOfPlaces, name='print_number_of_places'),
    path('routeNumberOfPlacesAgentprint/<int:pk>/', printRouteNumberOfPlacesAgent, name='print_num_pl_agent'),
    path('routeProductsprint/<int:pk>/', printRouteCountProducts, name='print_products'),

    path('route_select/', selectedRoute, name='selected_route'),
    path('route_location/', change_location, name='change_location'),


    path('ReceptionTransmission/', ListReceptionTransmission.as_view(), name='list_rt'),
    path('ReceptionTransmission/history/', ListReceptionTransmissionHistory.as_view(), name='list_rt_history'),
    path('ReceptionTransmission/history/<int:pk>/', ReceptionTransmissionContractHistory, name='rt_history_id'),
    path('ReceptionTransmission/RecTransCont/<int:pk>/', ReceptionTransmissionContract, name='rt_id'),
    path('create_RecTran/', ReceptionTransmissionAddView.as_view(), name='add_rt'),
    path('ReceptionTransmission/update_RecTran/<int:pk>/', ReceptionTransmissionEditView.as_view(), name='edit_rt'),
    path('delete_RecTran/<int:pk>/', recTrans_delete, name='delete_rt'),
    path('export/<int:pk>/', export_to_pdf, name='export_pdf'),
    path('search/', searchByBagNumber, name='search_recTran_url'),
    path('search2/', SeatsAndWeightReport, name='search2_recTran_url'),

    path('reg_places', RegistrationPlaceView.as_view(), name='reg_places'),
    path('reg_places_add', RegPlacesAddView.as_view(), name='reg_places_add'),
    path('edit/reg_places/<int:pk>/', RegPlacesEditView.as_view(), name='reg_places_edit'),
    path('delete/reg_places/<int:id>/', reg_places_delete, name='reg_places_delete'),

    path('directions', DirectionsView.as_view(), name='directions'),
    path('directions_add', DirectionAddView.as_view(), name='directions_add'),
    path('edit/directions/<int:pk>', DirectionEditView.as_view(), name='directions_edit'),
    path('delete/directions/<int:id>', directions_delete, name='directions_delete'),

    path('currency', CurrencyView.as_view(), name='currency'),
    path('currency_add', CurrencyAddView.as_view(), name='currency_add'),
    path('edit/currency/<int:pk>', CurrencyEditView.as_view(), name='currency_edit'),
    path('delete/currency/<int:id>', currency_delete, name='currency_delete'),

    path('service_price', ServicePriceView.as_view(), name='service_price'),
    path('service_price/add', ServicePriceAddView.as_view(), name='service_price_add'),
    path('service_price/view/<int:pk>', ServicePriceViewID.as_view(), name='service_price_view_id'),
    path('service_price/edit/<int:pk>', ServicePriceEditView.as_view(), name='service_price_edit'),
    path('delete/service_price/<int:id>', service_price_delete, name='service_price_delete'),

    path('financial_report/', FinancialReport.as_view(), name='financial_report'),
    path('checkBagNumber/', checkBagNumber, name='check_bagNum_jx'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sapat_cargo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from sapat_cargo import settings
urlpatterns = [
    path('main/', include("main.urls")),
    path('', include("user.urls")),
    path('route/', include('route.urls')),
    path('financial/', include("financial.urls")),
    path('admin/', admin.site.urls),
    path('user/', include("user.urls",)),
    path('systems/', include("systems.urls")),
    path('debits/', include("debits.urls",)),
    path('warehouse/', include("warehouse.urls",)),
    path('chaining/', include('smart_selects.urls')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

systems/urls.py
from django.urls import path
from .views import *
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'systems'
urlpatterns = [

    path('users', views.UsersView.as_view(), name='users'),
    path('user_add', views.UserAddView.as_view(), name='user_add'),

    path('user_edit/<int:pk>', views.UserEditView.as_view(), name='user_edit'),

    path('delete/user/<int:pk>', views.delete_user, name='user_delete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/extends/index.html
{% extends 'extends/base.html' %}
{% block menu %}
    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                 with font-awesome or any other icon font library -->
            <li class="nav-item">
                <a href="#" class="nav-link active">
                    <i class="nav-icon fas fa-newspaper"></i>
                    <p>
                        Контент
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{% url 'main:products' %}" class="nav-link active">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Список товаров</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'main:clients' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Клиенты</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'main:employees' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Сотрудники</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'main:contrageny' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Контрагены</p>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-truck"></i>
                    <p>
                        Рейсы <i class="fas fa-angle-left right"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{% url 'route:list_route_url' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Список</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'route:financial_report' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Финансовый отчет</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'route:list_rt' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Прием/передача</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'route:reg_places' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Места оформления</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'route:directions' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Направления</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'route:currency' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Валюты</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'route:service_price' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Цены сервисов</p>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="nav-item menu">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-cash-register"></i>
                    <p>
                        Финансы
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{% url 'financial:cash_box' %}" class="nav-link active">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Кассы</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'financial:reports' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Отчет</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'financial:articles' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Статьи</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'financial:operations' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Операции</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'financial:prepaid' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Авансы</p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="{% url 'financial:fines' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Штрафы</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'financial:work_pay' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Сдельная оплата</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'financial:loading_pay' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Оплата за погрузку</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'financial:salary' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Зарплата</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item menu">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-database"></i>
                    <p>
                        Склады
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{% url 'warehouse:list_warehouse' %}" class="nav-link active">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Список</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'warehouse:list_category' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Категории наименований</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'warehouse:list_naming' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Список наименований</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'warehouse:wh_operations' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Операции</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'warehouse:ostatok' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Остаток</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'warehouse:wh_report' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Отчет</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'warehouse:bag_report' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Отчет по мешкам</p>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="nav-item menu">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-calculator"></i>
                    <p>
                        Дебитировка
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{% url 'debits:report' %}" class="nav-link active">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Отчет</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'debits:list_income' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Приходник</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'debits:clientReport' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Отчет по клиентам</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'debits:clientReport_tonnage' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Отчет по клиентам - Тоннаж</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'debits:agentofclient' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Контрагенты клиента</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item menu">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-th"></i>
                    <p>
                        Cистема
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{% url 'systems:users' %}" class="nav-link active">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Пользователи</p>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
{% endblock %}

templates/extends/index_sub_admin.html
{% extends 'extends/base.html' %}
{% block menu %}
    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                 with font-awesome or any other icon font library -->
            <li class="nav-item menu-open">
                <a href="#" class="nav-link active">
                    <i class="nav-icon fas fa-newspaper"></i>
                    <p>
                        Контент
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{% url 'main:products' %}" class="nav-link active">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Список товаров</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'main:clients' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Клиенты</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'main:employees' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Сотрудники</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'main:contrageny' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Контрагены</p>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-truck"></i>
                    <p>
                        Рейсы <i class="fas fa-angle-left right"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{% url 'route:list_route_url' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Список</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'route:list_rt' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Прием/передача</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'route:service_price' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Цены сервисов</p>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
{% endblock %}