financial/urls.py
from django.urls import path
from .views import *
from .prints import *
from .search import *
from .salary import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'financial'
urlpatterns = [
    path('cash_box/', CashBoxView.as_view(), name='cash_box'),
    path('cash_box/print', printCashBoxes, name='cash_box_print'),
    path('cash_box_add/', CashBoxAddView.as_view(), name='cash_box_add'),

    path('reports/', Reports.as_view(), name='reports'),
    path('get_article/', getArticle, name='reports_article_js'),

    path('articles/', ArticlesView.as_view(), name='articles'),
    path('article/add/', ArticlesViewAdd.as_view(), name='article_add'),
    path('article/edit/<int:pk>/', ArticlesEditView.as_view(), name='article_edit'),
    path('article/delete/<int:id>/', article_delete, name='article_delete'),

    path('operations/', OperationsView.as_view(), name='operations'),

    path('operations/income/view/<int:pk>/', IncomeId.as_view(), name='operations_income_ID'),
    path('operations/consumption/view/<int:pk>', ConsumptionId.as_view(), name='operations_cons_ID'),
    path('operations/payroll/view/<int:pk>', PayrollID.as_view(), name='operations_payroll_ID'),
    path('operations/income/print/<int:pk>', IncomePrint.as_view(), name='operations_income_print'),

    path('operations/delete/<int:pk>', deleteOperations, name='operations_delete'),

    path('operations/income/client/add/', OperationsIncomeClientAdd.as_view(), name='operations_in_client_add'),
    path('operations/income/client/edit/<int:pk>/', OperationsIncomeClientEdit.as_view(), name='operations_in_client_edit'),

    path('operations/income/counterparty/add/', OperationsIncomeAgentAdd.as_view(), name='operations_in_agent_add'),
    path('operations/income/counterparty/edit/<int:pk>/', OperationsIncomeAgentEdit.as_view(), name='operations_in_agent_edit'),

    path('operations/income/various/add/', OperationsVarioustAdd.as_view(), name='operations_in_various_add'),
    path('operations/income/various/edit/<int:pk>', OperationsIncomeVariousEdit.as_view(), name='operations_in_various_edit'),

    path('operations/consumption/employee/add/', ConsumptionEmployeeAdd.as_view(), name='cons_employee_add'),
    path('operations/consumption/employee/edit/<int:pk>', ConsEmployeeEdit.as_view(), name='cons_employee_edit'),
    path('operations/consumption/employee/print/<int:pk>', consEmployee_print, name='cons_employee_print'),

    path('operations/consumption/agent/add/', ConsumptionAgentAdd.as_view(), name='cons_agent_add'),
    path('operations/consumption/agent/edit/<int:pk>', ConsumptionAgentEdit.as_view(), name='cons_agent_edit'),
    path('operations/consumption/agent/print/<int:pk>', consAgent_print, name='cons_agent_print'),

    path('operations/consumption/agent_of_client/', ConsAgentClientAdd.as_view(), name='cons_agent_client_add'),
    path('operations/consumption/agent_of_client/edit/<int:pk>', ConsAgentClientEdit.as_view(), name='cons_agent_client_edit'),
    path('operations/consumption/agent_of_client/print/<int:pk>', consAgentClient_print, name='cons_agent_client_print'),

    path('operations/consumption/various/', OperationsConsVarioustAdd.as_view(), name='cons_various_add'),
    path('operations/consumption/various/edit/<int:pk>', OperationsConsVarioustEdit.as_view(), name='cons_various_edit'),
    path('operations/consumption/various/print/<int:pk>', consVarious_print, name='cons_various_print'),

    path('operations/payroll/emp/add/', PaymentStatementEmployeeAddView.as_view(), name='payroll_emp_add'),
    path('operations/payroll/emp/edit/<int:pk>', PaymentStatementEmployeeEditView.as_view(), name='ps_emp_edit'),
    path('operations/payroll/emp/print/<int:pk>', psEmployee_print, name='ps_emp_print'),

    path('operations/payroll/agent/add/', PaymentStatementAgentAddView.as_view(), name='payroll_agent_add'),
    path('operations/payroll/agent/edit/<int:pk>', PaymentStatementAgentEditView.as_view(), name='ps_agent_edit'),
    path('operations/payroll/agent/print/<int:pk>', psAgent_print, name='ps_agent_print'),

    path('operations/consumption/cash_moving/', OperationsConsCashMovingAdd.as_view(), name='cons_cash_moving_add'),
    path('operations/consumption/cash_moving/<int:pk>', OperationsConsCashMovingID.as_view(),
         name='cons_cash_moving_ID'),
    path('operations/consumption/cash_moving/edit/<int:pk>', OperationsConsCashMovingEdit.as_view(),
         name='cons_cash_moving_edit'),
    path('operations/consumption/cash_moving/print/<int:pk>', consCashMoving_print, name='cons_cash_moving_print'),

    path('advance/', AdvanceView.as_view(), name='prepaid'),
    path('fines', FinesView.as_view(), name='fines'),

    path('work_pay', WorkPayView.as_view(), name='work_pay'),
    path('work_pay/emp/<int:pk>', WorkPayEmpView.as_view(), name='work_pay_emp'),

    path('loading_pay', LoadingPayView.as_view(), name='loading_pay'),
    path('loading_pay/emp/<int:pk>', LoadingPayEmpView.as_view(), name='loading_pay_emp'),

    path('salary', SalaryView.as_view(), name='salary'),
    path('salaryID/<int:pk>', SalaryViewID.as_view(), name='salary_id'),
    path('printsalary/<int:pk>', printSalaryID, name='salary_print'),
    path('salary/add/', SalaryAddView.as_view(), name='salary_add'),
    path('salary/edit/<int:pk>', SalaryEditView.as_view(), name='salary_edit'),
    path('salary/delete/<int:pk>', deleteSalary, name='salary_delete'),

    path('salary/emp/', showEmployeeModal, name='salary_show_emp_jx'),
    path('salary/emp_edit/', showEmployeeEditModal, name='salary_show_emp_edit_jx'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'main'

urlpatterns = [
    path('', views.HomePage.as_view(), name='home_page'),
    path('products', views.Products.as_view(), name='products'),
    path('product/edit/<int:pk>', ProductEditView.as_view(), name='product_edit'),
    path('product/delete/<int:pk>', deleteProduct, name='delete_product'),
    path('product/add/', views.ProductAddView.as_view(), name='product_add'),

    path('clients', views.ClientListView.as_view(), name='clients'),
    path('client/add/', views.ClientAddView.as_view(), name='client_add'),
    path('client/edit/<int:pk>', ClientEditView.as_view(), name='client_edit'),
    path('clients/delete/<int:pk>', delete_client, name='delete_client'),

    #path('senders', SenderListView.as_view(), name='senders'),
    path('senders/addjx/', add_sender, name='sender_add_ajax'),
    path('load_senders/', load_senders, name='load_senders_ajax'),
    path('senders/edit/<int:pk>', SenderEditView.as_view(), name='sender_edit'),
    #path('senders/delete/<int:pk>', delete_sender, name='delete_sender'),

    path('employees', EmployeeListView.as_view(), name='employees'),
    path('employee/add', EmployeeAdd.as_view(), name='employee_add'),
    path('employees/edit/<int:pk>', EmployeeEditView.as_view(), name='employee_edit'),
    path('delete/employees/<int:pk>', delete_employee, name='delete_employee'),

    path('contrageny', AgentOfClients.as_view(), name='contrageny'),
    path('contrageny/add', AgentOfClientAddView.as_view(), name='contrageny_add'),
    path('contrageny/edit/<int:pk>', AgentOfClientEditView.as_view(), name='contragenty_edit'),
    path('contrageny/delete/<int:pk>', delete_agenty, name='delete_contragenty'),

]

sapat_cargo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from sapat_cargo import settings
urlpatterns = [
    path('main/', include("main.urls")),
    path('', include("user.urls")),
    path('route/', include('route.urls')),
    path('financial/', include("financial.urls")),
    path('admin/', admin.site.urls),
    path('user/', include("user.urls",)),
    path('systems/', include("systems.urls")),
    path('debits/', include("debits.urls",)),
    path('warehouse/', include("warehouse.urls",)),
    path('chaining/', include('smart_selects.urls')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

financial/models.py
import datetime
from datetime import date
from django.db import models
from main.models import Client, Employee, AgentOfClient
from user.models import User

class CashBox(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название', unique=True,
                            error_messages={"unique": "Такая касса уже существует"})
    description = models.TextField(verbose_name='Описание', null=True, blank=True)

    def __str__(self):
        return self.name

type = (
        (1, 'Приходник'),
        (2, 'Расходник'),
    )

class Articles(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название', unique=True,
                            error_messages={"unique": "Такая статья уже существует"})
    type = models.IntegerField(choices=type, verbose_name="Тип")
    description = models.TextField(verbose_name='Описание', null=True, blank=True)

    def __str__(self):
        return self.name

class Salary(models.Model):
    currency = models.ForeignKey('route.Currency', on_delete=models.CASCADE)
    dateFrom = models.DateField(verbose_name='Дата От')
    dateTo = models.DateField(verbose_name='Дата До')
    inspection = models.FloatField(default=12.0)
    packing = models.FloatField(default=36.0)
    loading = models.FloatField(default=15.0)

class SalaryCurrency(models.Model):
    currency = models.ForeignKey('route.Currency', on_delete=models.CASCADE)
    curs = models.FloatField(default=0.0)
    salary = models.ForeignKey(Salary, on_delete=models.CASCADE)

class SalaryInner(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    debt = models.FloatField(verbose_name='Долг', default=0.0)
    oklad = models.FloatField(verbose_name='оклад', default=0.0)
    premiums = models.FloatField(verbose_name='премии', default=0.0)
    other = models.FloatField(verbose_name='прочее', default=0.0)
    interest = models.FloatField(verbose_name='проценты', default=0.0)
    issuance = models.FloatField(verbose_name='Выдача', default=0.0)
    fine = models.FloatField(verbose_name='Штрафы', default=0.0)
    advance = models.FloatField(verbose_name='Авансы', default=0.0)
    services = models.FloatField(verbose_name='Услуги', default=0.0)
    totalSL = models.FloatField(verbose_name='Итого ЗП', default=0.0)
    remainder = models.FloatField(verbose_name='Остаток', default=0.0)
    total = models.FloatField(verbose_name='итого', default=0.0)
    salary = models.ForeignKey(Salary, on_delete=models.CASCADE)

class ServicesSalary(models.Model):
    country = models.ForeignKey('route.Direction', on_delete=models.CASCADE, verbose_name='')
    inspection = models.FloatField(default=0.0, verbose_name="досмотр")
    packing = models.FloatField(default=0.0, verbose_name="упаковка")
    loading = models.FloatField(default=0.0, verbose_name="погрузка")
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    salary = models.ForeignKey(Salary, on_delete=models.CASCADE)

type2 = (
        (1, 'Приходник'),
        (2, 'Расходник'),
        (3, 'Платежная ведомость'),
        (4, 'Перемещение')
    )

type3 = (
        (1, 'Приходник клиент'),
        (2, 'Приходник контаргент'),
        (3, 'Приходник разное'),
        (4, 'Расходник сотрудник'),
        (5, 'Расходник контаргент'),
        (6, 'Расходник контаргенту клиента'),
        (7, 'Расходник разное'),
        (8, 'Платежная ведомость контаргент'),
        (9, 'Платежная ведомость сотрудник'),
        (10, 'Перемещение')
    )

class Operations(models.Model):
    date = models.DateTimeField(verbose_name='Дата', default=datetime.datetime.today())
    cash = models.ForeignKey(CashBox, related_name='cash', on_delete=models.CASCADE)
    article = models.ForeignKey(Articles, on_delete=models.CASCADE, verbose_name='Статья', null=True, blank=True)
    currency = models.ForeignKey("route.Currency", on_delete=models.CASCADE, verbose_name='Валюта')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)
    route = models.ForeignKey("route.Route", on_delete=models.CASCADE, blank=True, null=True)

    client = models.ForeignKey(Client, on_delete=models.CASCADE, blank=True, null=True)
    agent = models.ForeignKey(AgentOfClient, on_delete=models.CASCADE, blank=True, null=True)
    various = models.CharField(max_length=50, verbose_name='Разное', blank=True, null=True)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, blank=True, null=True)
    agentClient = models.ForeignKey('debits.ClientContrAgents', on_delete=models.CASCADE, blank=True, null=True)
    cash_sender = models.ForeignKey(CashBox, related_name='cash_sender', on_delete=models.CASCADE, blank=True, null=True)
    sum = models.FloatField(default=0.0, blank=True, null=True)
    type = models.IntegerField(choices=type2, verbose_name="Тип")
    type2 = models.IntegerField(choices=type3, null=True)
    added_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

class OperationsInner(models.Model):
    check = models.CharField(max_length=50, blank=True, null=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, blank=True, null=True)
    route = models.ForeignKey("route.Route", on_delete=models.CASCADE, blank=True, null=True)
    sum = models.FloatField(verbose_name="Сумма", default=0.0)
    article = models.ForeignKey(Articles, on_delete=models.CASCADE, blank=True, null=True)
    count = models.FloatField(default=0.0, blank=True, null=True)
    price = models.FloatField(default=0.0, blank=True, null=True)
    note = models.CharField(max_length=30, blank=True, null=True)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, blank=True, null=True)
    agent = models.ForeignKey('main.AgentOfClient', on_delete=models.CASCADE, blank=True, null=True)

    inner = models.ForeignKey(Operations, on_delete=models.CASCADE)

templates/financial/pages/operations.html
{% extends base_template_name %}
{% load static %}
{% load widget_tweaks %}

{% block content_header %}
    <div class="content-header">
        <div class="container-fluid">

            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Список операций</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'main:home_page' %}">Главная</a></li>
                        <li class="breadcrumb-item active">Список операций</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="card card-primary card-outline">
        <div class="card-header">
            <div class="row">
                <div class="btn-group col-auto">
                    <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Приходник
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'financial:operations_in_client_add' %}"> <i class="fa fa-fw fa-plus-square"></i> Клиент</a>
                        <a class="dropdown-item" href="{% url 'financial:operations_in_agent_add' %}"> <i class="fa fa-fw fa-plus-square"></i> Контрагент</a>
                        <a class="dropdown-item" href="{% url 'financial:operations_in_various_add' %}"> <i class="fa fa-fw fa-plus-square"></i> Разное</a>
                    </div>
                </div>

                <div class="btn-group col-auto">
                    <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Расходник
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'financial:cons_employee_add' %}"> <i class="fa fa-fw fa-minus-square"></i> Сотруднику </a>
                        <a class="dropdown-item" href="{% url 'financial:cons_agent_add' %}"> <i class="fa fa-fw fa-minus-square"></i> Контрагенту</a>
                        <a class="dropdown-item" href="{% url 'financial:cons_agent_client_add' %}"> <i class="fa fa-fw fa-minus-square"></i> Контрагенту клиента</a>
                        <a class="dropdown-item" href="{% url 'financial:cons_various_add' %}"> <i class="fa fa-fw fa-minus-square"></i> Разное</a>
                    </div>
                </div>
                <div class="btn-group col-auto">
                    {% if user.role == 4 %}
                    <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Разное
                    </button>
                    {% endif %}
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'financial:cons_cash_moving_add' %}"> <i class="fa fa-fw fa-retweet"></i> Перемещение </a>
                        <a class="dropdown-item" href="{% url 'financial:payroll_agent_add' %}"> <i class="fa fa-fw fa-object-group"></i> Платежная ведомость (Контрагенты)</a>
                        <a class="dropdown-item" href="{% url 'financial:payroll_emp_add' %}"> <i class="fa fa-fw fa-object-group"></i> Платежная ведомость (Сотрудники)</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            <table class="simple_table" border="1">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Дата</th>
                    <th>Касса</th>
                    <th>Касса отправитель</th>
                    <th>Тип операций</th>
                    <th>Сумма</th>
                    <th>Валюта </th>
                    <th>Статья</th>
                    <th></th>
                </tr>

                <tr>
                    <form method="get">
                        <td>{{ form.id|add_class:"form-control" }}</td>
                        <td>{{ form.date|add_class:"form-control" }}</td>
                        <td>{{ form.cash|add_class:"form-control" }}</td>
                        <td>{{ form.cash_sender|add_class:"form-control" }}</td>
                        <td>{{ form.type|add_class:"form-control" }}</td>
                        <td>{{ form.sum|add_class:"form-control" }}</td>
                        <td>{{ form.currency|add_class:"form-control" }}</td>
                        <td>{{ form.article|add_class:"form-control" }}</td>

                        <td align="center">
                            <button class="btn btn-success" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </td>
                    </form>
                </tr>

                </thead>
                <tbody>



                {% for ob in page_obj %}

                    <tr>
                        <td>{{ ob.pk }}</td>
                        <td>{{ ob.date }}</td>
                        <td>{{ ob.cash.name }}</td>
                        <td>
                            {% if ob.cash_sender %}
                                {{ ob.cash_sender }}
                            {% endif %}
                        </td>
                        <td>{{ ob.get_type_display }}</td>
                        <td>{{ ob.sum }}</td>
                        <td>{{ ob.currency.name }}</td>
                        <td>{{ ob.article.name }}</td>
                        <td>

                            {% if ob.type == 1 %}
                                <a href="{% url 'financial:operations_income_ID' ob.pk %}"> <i class="fa fa-eye"></i></a>
                            {% elif ob.type == 2 %}
                                <a href="{% url 'financial:operations_cons_ID' ob.pk %}"> <i class="fa fa-eye"></i></a>
                            {% elif ob.type == 3 %}
                                <a href="{% url 'financial:operations_payroll_ID' ob.pk %}"> <i class="fa fa-eye"></i></a>
                            {% elif ob.type == 4%}
                                <a href="{% url 'financial:cons_cash_moving_ID' ob.pk %}"> <i class="fa fa-eye"></i></a>
                            {% endif %}
                        {% if user.role != 4 %}

                            {% if ob.type2 == 1 %}
                                <a href="{% url 'financial:operations_in_client_edit' ob.pk %}">
                                    <i class="fa fa-fw fa-edit"></i>
                                </a>

                            {% elif ob.type2 == 2 %}
                                <a href="{% url 'financial:operations_in_agent_edit' ob.pk %}">
                                    <i class="fa fa-fw fa-edit"></i>
                                </a>

                            {% elif ob.type2 == 3 %}
                                <a href="{% url 'financial:operations_in_various_edit' ob.pk %}">
                                    <i class="fa fa-fw fa-edit"></i> </a>

                            {% elif ob.type2 == 4 %}
                                <a href="{% url 'financial:cons_employee_edit' ob.pk %}">
                                    <i class="fa fa-fw fa-edit"></i></a>

                            {% elif ob.type2 == 5 %}
                                <a href="{% url 'financial:cons_agent_edit' ob.pk %}">
                                    <i class="fa fa-fw fa-edit"></i></a>

                            {% elif ob.type2 == 6 %}
                                <a href="{% url 'financial:cons_agent_client_edit' ob.pk %}">
                                    <i class="fa fa-fw fa-edit"></i> </a>

                            {% elif ob.type2 == 7 %}
                                <a href="{% url 'financial:cons_various_print' ob.pk %}">
                                    <i class="fa fa-fw fa-edit"></i> </a>

                            {% elif ob.type2 == 8 %}
                                <a href="{% url 'financial:ps_agent_edit' ob.pk %}">
                                    <i class="fa fa-fw fa-edit"></i></a>

                            {% elif ob.type2 == 9 %}
                                <a href="{% url 'financial:ps_emp_edit' ob.pk %}">
                                    <i class="fa fa-fw fa-edit"></i></a>

                            {% elif ob.type2 == 10 %}
                                <a href="{% url 'financial:cons_cash_moving_edit' ob.pk %}">
                                    <i class="fa fa-fw fa-edit"></i></a>
                            {% endif %}

                            <a class="confirm-delete" href="{% url 'financial:operations_delete' ob.pk %}"> <i class="fa fa-trash-alt"></i></a>
                        {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% include 'paginator.html' %}

    </div>

{% endblock %}

templates/financial/pages/payroll.html
{% extends base_template_name %}
{% block css %}
    <style>
        .font_size{font-size: 92%;}
    </style>
{% endblock %}
{% block content_header %}
    <div class="content-header">
        <div class="container-fluid">

            <div class="row mb-2">
                <div class="col-sm-6">
                    <h6 class="m-0">Просмотр платежной ведомости</h6>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'main:home_page' %}">Главная</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'financial:operations' %}">Список операций</a></li>
                        <li class="breadcrumb-item active">Просмотр платежной ведомости</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="card card-primary card-outline font_size">
        <div class="card-body">
            <table width="100%">
                <tr>
                    <td colspan="3" width="100%" align="center"><h4>Платежная ведомость</h4></td>
                </tr>
                <tr>
                    <td width="50%"></td>
                    <td align="right">Номер документа: <b>{{ obj.pk }}</b></td>
                    <td align="right">Дата составления: <b>{{ obj.date|date:"c" }}</b></td>
                </tr>
                <tr>
                    <td width="50%" align="right">Сумма: &nbsp;&nbsp;&nbsp;&nbsp;<b>{{ obj.sum }} {{ obj.currency.name }}</b></td>
                    <td align="right"></td>
                    <td align="right"></td>
                </tr>
            </table>
            <br>
            <?php $i = 1; $summ = 0; ?>
            <table border="1" width="100%">
                <tr>
                    <td>&nbsp;</td>
                    <td colspan="5">&nbsp;</td>
                </tr>
                <tr>
                    <td><b>№</b></td>
                    <td><b>Получатель</b></td>
                    <td><b>Статья</b></td>
                    <td><b>Сумма({{ obj.currency.name }})</b></td>
                    <td><b>Подпись</b></td>
                </tr>
                {% for ob in obj_inner %}
                    <tr>
                        <td>{{ ob.pk }}</td>
                        <td>
                            {% if ob.inner.type2 == 8 %}
                                {{ ob.agent.fullname }}
                            {% elif ob.inner.type2 == 9 %}
                                {{ ob.employee.fullname }}
                            {% endif %}
                        </td>
                        <td>{{ obj.article.name }}</td>
                        <td align="right">{{ ob.sum }} {{ obj.currency.name }}</td>
                        <td></td>
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="2" align="center"><b>Итого:</b></td>
                    <td></td>

                    <td align="right"><b>{{ obj.sum }} {{ obj.currency.name }}</b></td>
                    <td></td>
                </tr>
            </table>
            <BR><BR><BR>
            <table width="100%">
                <tr>
                    <td width="33%">Выдал кассир</td>
                    <td width="33%"><div style="border-bottom: 1px solid #000; margin: 20px 20px 0 20px;"><b>{{ obj.added_by.first_name }}&nbsp;{{ obj.added_by.last_name }}</b></div></td>
                    <td width="33%"><div style="border-bottom: 1px solid #000; margin: 40px 20px 0 20px;"></div></td>
                </tr>
                <tr>
                    <td width="33%">Главный бухгалтер</td>
                    <td width="33%"><div style="border-bottom: 1px solid #000; margin: 20px 20px 0 20px;"></div></td>
                    <td width="33%"><div style="border-bottom: 1px solid #000; margin: 20px 20px 0 20px;"></div></td>
                </tr>
            </table>
            <BR>


            {% if user.role == -1 %}
                {% if obj.type2 == 8 %}
                        <a class="btn btn-success print" href="{% url 'financial:ps_agent_print' obj.pk %}"><i class="fa fa-fw fa-print"></i> Печать</a>
                 {% elif obj.type2 == 9 %}
                        <a class="btn btn-success print" href="{% url 'financial:ps_emp_print' obj.pk %}"><i class="fa fa-fw fa-print"></i> Печать</a>
                 {% endif %}

            {% elif user.role == 1 or user.role == 6 or user.role == 3 or user.role == 4 %}

            {% if obj.type2 == 8 %}
                <div class="btn-group">
                    <a class="btn btn-success print" href="{% url 'financial:ps_agent_print' obj.pk %}"><i class="fa fa-fw fa-print"></i> Печать</a>
                    <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <span class="caret"></span>
                        <span class="sr-only">Toggle Dropdown</span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li><a class="dropdown-item" href="{% url 'financial:ps_agent_edit' obj.pk %}"><i class="fa fa-fw fa-edit"></i> Редактировать</a></li>
                    </ul>
                </div>
            {% elif obj.type2 == 9 %}
                <div class="btn-group">
                    <a class="btn btn-success print" href="{% url 'financial:ps_emp_print' obj.pk %}"><i class="fa fa-fw fa-print"></i> Печать</a>
                    <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <span class="caret"></span>
                        <span class="sr-only">Toggle Dropdown</span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li><a class="dropdown-item" href="{% url 'financial:ps_emp_edit' obj.pk %}"><i class="fa fa-fw fa-edit"></i> Редактировать</a></li>
                    </ul>
                </div>
            {% endif %}
        {% endif %}
        </div>
    </div>
{% endblock %}