main/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'main'

urlpatterns = [
    path('', views.HomePage.as_view(), name='home_page'),
    path('products', views.Products.as_view(), name='products'),
    path('product/edit/<int:pk>', ProductEditView.as_view(), name='product_edit'),
    path('product/delete/<int:pk>', deleteProduct, name='delete_product'),
    path('product/add/', views.ProductAddView.as_view(), name='product_add'),

    path('clients', views.ClientListView.as_view(), name='clients'),
    path('client/add/', views.ClientAddView.as_view(), name='client_add'),
    path('client/edit/<int:pk>', ClientEditView.as_view(), name='client_edit'),
    path('clients/delete/<int:pk>', delete_client, name='delete_client'),

    #path('senders', SenderListView.as_view(), name='senders'),
    path('senders/addjx/', add_sender, name='sender_add_ajax'),
    path('load_senders/', load_senders, name='load_senders_ajax'),
    path('senders/edit/<int:pk>', SenderEditView.as_view(), name='sender_edit'),
    #path('senders/delete/<int:pk>', delete_sender, name='delete_sender'),

    path('employees', EmployeeListView.as_view(), name='employees'),
    path('employee/add', EmployeeAdd.as_view(), name='employee_add'),
    path('employees/edit/<int:pk>', EmployeeEditView.as_view(), name='employee_edit'),
    path('delete/employees/<int:pk>', delete_employee, name='delete_employee'),

    path('contrageny', AgentOfClients.as_view(), name='contrageny'),
    path('contrageny/add', AgentOfClientAddView.as_view(), name='contrageny_add'),
    path('contrageny/edit/<int:pk>', AgentOfClientEditView.as_view(), name='contragenty_edit'),
    path('contrageny/delete/<int:pk>', delete_agenty, name='delete_contragenty'),

]

sapat_cargo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from sapat_cargo import settings
urlpatterns = [
    path('main/', include("main.urls")),
    path('', include("user.urls")),
    path('route/', include('route.urls')),
    path('financial/', include("financial.urls")),
    path('admin/', admin.site.urls),
    path('user/', include("user.urls",)),
    path('systems/', include("systems.urls")),
    path('debits/', include("debits.urls",)),
    path('warehouse/', include("warehouse.urls",)),
    path('chaining/', include('smart_selects.urls')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

warehouse/urls.py
from django.urls import path
from . import views
from .views import *
from .print import *

app_name = 'warehouse'

urlpatterns = [
    path('storage/', WarehouseListView.as_view(), name='list_warehouse'),
    path('storage/add/', WarehouseAddView.as_view(), name='warehouse_add'),
    path('storage/edit/<int:pk>/', WarehouseUpdateView.as_view(), name='warehouse_update'),
    path('storage/delete/<int:pk>/', deleteWarehose, name='warehouse_delete'),

    path('category/', CategoryListView.as_view(), name='list_category'),
    path('category/add/', CategoryAddView.as_view(), name='category_add'),
    path('category/edit/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', deleteCategory, name='category_delete'),

    path('naming/', NamingListView.as_view(), name='list_naming'),
    path('naming/add/', NamingAddView.as_view(), name='naming_add'),
    path('naming/edit/<int:pk>/', NamingUpdateView.as_view(), name='naming_update'),
    path('naming/delete/<int:pk>/', deleteNaming, name='naming_delete'),

    path('bag_report/', views.BagReportView.as_view(), name='bag_report'),
    path('bag_report/load_routes', load_routes, name='ajax_load_routes'),

    path('wh_report', views.WHReportView.as_view(), name='wh_report'),
    path('ostatok', views.OstatokView.as_view(), name='ostatok'),
    path('selectListname/', selectListName, name='select_listName_url'),

    path('wh_operations/', views.WHOperatiosView.as_view(), name='wh_operations'),

    path('wh_incomeId/<int:pk>/', IncomeWarehouseView.as_view(), name='wh_incomeId'),
    path('wh_incomeCash/<int:pk>/', IncomeWarehouseCashierView.as_view(), name='wh_income_cashier'),

    path('wh_income_add/', WHIncomeAddView.as_view(), name='wh_income_add'),
    path('wh_income_edit/<int:pk>/', WHIncomeEditView.as_view(), name='wh_income_edit'),
    path('wh_income_delete/<int:pk>/', operationDelete, name='wh_income_delete'),
    path('wh_incomePrint/<int:pk>/', incomeWarehousePrint, name='wh_incomePrint'),
    path('wh_in_cash_Print/<int:pk>/', incomeWarehouseCashierPrint, name='wh_in_cash_Print'),


    path('wh_consumption_add/', WHConsumptionAddView.as_view(), name='wh_consumption_add'),
    path('wh_consumption_edit/<int:pk>/', WHConsumptionEditView.as_view(), name='wh_consumption_edit'),
    path('wh_consumption_delete/<int:pk>/', operationDelete, name='wh_consumption_delete'),
    path('wh_consumptionID/<int:pk>/', ConsumablesWarehouseView.as_view(), name='wh_consumptionId'),
    path('wh_consumptionPrint/<int:pk>/', consumablesWarehousePrint, name='wh_consumptionPrint'),

    path('wh_moving_add/', WHMovingAddView.as_view(), name='wh_moving_add'),
    path('wh_moving_edit/<int:pk>/', WHMovingEditView.as_view(), name='wh_moving_edit'),
    path('wh_moving_delete/<int:pk>/', operationDelete, name='wh_moving_delete'),
    path('wh_movingId/<int:pk>/', MovingWarehouseView.as_view(), name='wh_movingId'),
    path('wh_movingPrint/<int:pk>/', movingWarehousePrint, name='wh_movingPrint'),
]

warehouse/models.py
from django.db import models
from financial.models import Articles
from smart_selects.db_fields import ChainedForeignKey

from route.models import Route
from main.models import Client
from datetime import date
from user.models import User

# склад
class AddList(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название', unique=True,
                             error_messages={"unique": "Склад с таким именем уже существует"})
    content = models.TextField(verbose_name='Описание', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'список'
        verbose_name_plural = 'списки'

# Категория
class CategoryName(models.Model):
    category_item = [
        ('литр', 'литр'),
        ('штук', 'штук'),
        ('килограмм', 'килограмм')
    ]
    title = models.CharField(max_length=250, verbose_name='Название', unique=True,
                             error_messages={"unique": "Категория к складу с таким именем уже существует"})
    unit = models.CharField(max_length=10, choices=category_item, verbose_name='единица измерений')

    def __str__(self):
        return self.title

# Наимование
class ListName(models.Model):
    title = models.CharField(max_length=250, verbose_name='Название', unique=True,
                             error_messages={"unique": "Такое наименование уже существует"})
    category = models.ForeignKey(CategoryName, on_delete=models.CASCADE, verbose_name='Категория')

    def __str__(self):
        return self.title

type = (
        (1, 'Приходник'),
        (2, 'Расходник'),
        (3, 'Перемещение')
    )

class WarehouseOperation(models.Model):
    date = models.DateField(verbose_name='Дата', default=date.today)
    warehouse = models.ForeignKey(AddList, related_name='warehouse', on_delete=models.CASCADE)
    wh_article = models.ForeignKey(Articles, on_delete=models.CASCADE, blank=True, null=True)
    from_warehouse = models.ForeignKey(AddList, related_name='from_warehouse', on_delete=models.CASCADE,
                                       blank=True, null=True)
    route = models.ForeignKey(Route, on_delete=models.CASCADE, verbose_name='ID рейса',
                              blank=True, null=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='Клиент',
                               null=True, blank=True)
    sum = models.FloatField(default=0.0)
    type = models.IntegerField(choices=type, verbose_name="Тип")
    added_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True) # ONDOLOT

class WarehouseOperationInner(models.Model):
    category = models.ForeignKey(CategoryName, on_delete=models.CASCADE, verbose_name='Категория')
    name = ChainedForeignKey(ListName, chained_field='category', chained_model_field="category",
                             auto_choose=True, show_all=False)
    sum = models.FloatField(verbose_name='Количество', default=0.0,)
    price = models.FloatField(verbose_name='цена', default=0.0, blank=True, null=True)
    inner = models.ForeignKey(WarehouseOperation, on_delete=models.CASCADE)

# class StockBalance(models.Model):
#     warehouse = models.ForeignKey(AddList, on_delete=models.CASCADE)
#     naming = models.ForeignKey(ListName, on_delete=models.CASCADE)
#     total = models.FloatField(default=0)

warehouse/forms.py
from django.forms import ModelForm, DateInput
from .models import *
from django import forms
from djangoformsetjs.utils import formset_media_js
from route.models import Direction
from django.forms import formset_factory, inlineformset_factory

my_default_errors = {
    'required': 'Поле обязательно для заполнения',
    'invalid': 'Введите допустимое значение',
}

class AddListForm(ModelForm):
    required_css_class = 'required2'
    class Meta:
        model = AddList
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(AddListForm, self).__init__(*args, **kwargs)
        self.fields['content'].widget.attrs['id'] = 'summernote'

class CategoryNameForm(ModelForm):
    required_css_class = 'required2'

    class Meta:
        model = CategoryName
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CategoryNameForm, self).__init__(*args, **kwargs)
        self.fields['unit'].widget.attrs['class'] = 'select2'

class ListNameForm(ModelForm):
    required_css_class = 'required2'

    class Meta:
        model = ListName
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        super(ListNameForm, self).__init__(*args, **kwargs)
        self.fields['category'].widget.attrs['class'] = 'select2'

# --------------------------------------------------------------------

class WHIncomeForm(forms.ModelForm):
    class Meta:
        model = WarehouseOperation
        fields = ['date', 'warehouse', 'wh_article', 'sum', 'type']
        widgets = {'date': DateInput(attrs={'type': 'date'}, format=('%Y-%m-%d'))}

    def __init__(self, *args, **kwargs):
        super(WHIncomeForm, self).__init__(*args, **kwargs)
        self.fields['wh_article'].queryset = Articles.objects.filter(type=1)
        self.fields['type'].initial = 1
        self.fields['type'].widget = forms.HiddenInput()

        self.fields['wh_article'].required = True
        self.fields['sum'].widget.attrs['readonly'] = True

class WHIncomeInnerForm(forms.ModelForm):
    class Meta:
        model = WarehouseOperationInner
        fields = '__all__'
        widgets = {'category': forms.Select(attrs={'onchange': 'SetListName(this.id);'}),
                   'sum': forms.NumberInput(attrs={'oninput': 'controllerSumWarehouse();'})}

        error_messages = {
            'category': my_default_errors,
            'name': my_default_errors,
            'sum': my_default_errors,
            'price': my_default_errors}

    def __init__(self, *arg, **kwarg):
        super(WHIncomeInnerForm, self).__init__(*arg, **kwarg)
        self.empty_permitted = False
        self.fields['price'].required = True

    class Media(object):
        js = formset_media_js

WHIncomeInnerFormSet = inlineformset_factory(WarehouseOperation, WarehouseOperationInner,
                                             form=WHIncomeInnerForm, extra=1, can_delete=True)
WHIncomeInnerFormSet2 = inlineformset_factory(WarehouseOperation, WarehouseOperationInner,
                                              form=WHIncomeInnerForm, extra=0, can_delete=True)


# --------------------------------------------------------------------
class WHConsumptionForm(ModelForm):
    class Meta:
        model = WarehouseOperation
        exclude = ('from_warehouse', 'added_by')
        widgets = {'date': DateInput(attrs={'type': 'date'}, format=('%Y-%m-%d'))}

    def __init__(self, *args, **kwargs):
        super(WHConsumptionForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

        self.fields['wh_article'].queryset = Articles.objects.filter(type=2)
        self.fields['type'].initial = 2
        self.fields['type'].widget = forms.HiddenInput()

        self.fields['wh_article'].required = True
        self.fields['route'].required = True
        self.fields['sum'].widget.attrs['readonly'] = True

class WHConsumptionInnerForm(forms.ModelForm):
    class Meta:
        model = WarehouseOperationInner
        fields = '__all__'
        widgets = {'category': forms.Select(attrs={'onchange': 'SetListName(this.id);'}),
                   'sum': forms.NumberInput(attrs={'oninput': 'controllerSumWarehouse();'})}
        error_messages = {
            'category': my_default_errors,
            'name': my_default_errors,
            'sum': my_default_errors,
            'price': my_default_errors
        }
    def __init__(self, *arg, **kwarg):
        super(WHConsumptionInnerForm, self).__init__(*arg, **kwarg)
        self.empty_permitted = False
        self.fields['price'].required = True

    class Media(object):
        js = formset_media_js

WHConsumptionFormSet = inlineformset_factory(WarehouseOperation, WarehouseOperationInner,
                                             form=WHConsumptionInnerForm, extra=1, can_delete=True)
WHConsumptionFormSet2 = inlineformset_factory(WarehouseOperation, WarehouseOperationInner,
                                              form=WHConsumptionInnerForm, extra=0, can_delete=True)

# --------------------------------------------------------------------

class WHMovingForm(ModelForm):
    class Meta:
        model = WarehouseOperation
        fields = ['date', 'warehouse', 'from_warehouse', 'sum', 'type']
        widgets = {'date': DateInput(attrs={'type': 'date'}, format=('%Y-%m-%d'))}

    def __init__(self, *args, **kwargs):
        super(WHMovingForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

        self.fields['type'].initial = 3
        self.fields['type'].widget = forms.HiddenInput()

        self.fields['sum'].widget.attrs['readonly'] = True

class WHMovingInnerForm(forms.ModelForm):
    class Meta:
        model = WarehouseOperationInner
        exclude = ('price', )
        widgets = {'category': forms.Select(attrs={'onchange': 'SetListName(this.id);'}),
                   'sum': forms.NumberInput(attrs={'oninput': 'controllerSumWarehouse();'})}
        error_messages = {
            'category': my_default_errors,
            'name': my_default_errors,
            'sum': my_default_errors
        }

    class Media(object):
        js = formset_media_js

    def __init__(self, *arg, **kwarg):
        super(WHMovingInnerForm, self).__init__(*arg, **kwarg)
        self.empty_permitted = False



WHMovingFormSet = inlineformset_factory(WarehouseOperation, WarehouseOperationInner, form=WHMovingInnerForm, extra=1, can_delete=True)
WHMovingFormSet2 = inlineformset_factory(WarehouseOperation, WarehouseOperationInner, form=WHMovingInnerForm, extra=0, can_delete=True)

# --------------------------------------------------------------------

Operation_CHOICES = (
    ("1", "Приходник"),
    ("2", "Расходник"),
    ("3", "Перемещение"))

class WHReportForm(forms.Form):
    warehouse = forms.ModelChoiceField(queryset=AddList.objects.all(), label='Склад')
    naming = forms.ModelChoiceField(queryset=ListName.objects.all(), label='Наименование')
    operation = forms.ChoiceField(choices=Operation_CHOICES, label="Операция")
    dateFrom = forms.DateField(label="Дата ОТ", widget=DateInput(attrs={'type': 'date'}, format=('%Y-%m-%d')))
    dateTo = forms.DateField(label="Дата ДО", widget=DateInput(attrs={'type': 'date'}, format=('%Y-%m-%d')))


class BagReportForm(forms.Form):
    warehouse = forms.ModelChoiceField(queryset=AddList.objects.all())
    operation = forms.ChoiceField(choices=Operation_CHOICES)
    direction = forms.ModelChoiceField(queryset=Direction.objects.all(), required=False)
    dateFrom = forms.DateField(widget=DateInput(attrs={'type': 'date'}, format=('%Y-%m-%d')))
    dateTo = forms.DateField(widget=DateInput(attrs={'type': 'date'}, format=('%Y-%m-%d')))
    routeFrom = forms.ChoiceField(choices='', required=False)
    routeTo = forms.ChoiceField(choices='', required=False)

class OstatokForm(forms.Form):
    warehouse = forms.ModelChoiceField(queryset=AddList.objects.all())

templates/warehouse/pages/category.html
{% extends 'extends/index.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content_header %}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h3 class="m-0">Список категорий наименований</h3>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'main:home_page' %}">Главная</a></li>
                        <li class="breadcrumb-item active">Список категорий наименований</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="card card-primary card-outline">
        <div class="card-header">
            <a href="{% url 'warehouse:category_add' %}">
                <button type="button" class="btn btn-success">Добавить </button>
            </a>
        </div>

        <div class="card-body">

            <table class="table table-bordered table-hover" style="font-size: 90%">
                <thead>
                <tr>
                    <th>ID </th>
                    <th>Название</th>
                    <th> </th>
                </tr>
                </thead>
                <tbody>

                <tr>
                    <form method="get">
                        <td>{{ form.id|add_class:"form-control" }}</td>
                        <td>{{ form.title|add_class:"form-control" }}</td>
                        <td align="center">
                            <button class="btn btn-success" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </td>
                    </form>
                </tr>

                    {% for i in page_obj %}
                        <tr>
                            <td> {{ i.id }}</td>
                            <td> {{ i.title }}</td>
                            <td>
                                <a href="{% url 'warehouse:category_update' i.id %}">
                                    <i class="fa fa-edit"></i>
                                </a> &nbsp;
                                <a class="confirm-delete" href="{% url 'warehouse:category_delete' i.id %}">
                                    <i class="fa fa-trash-alt"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% include 'paginator.html' %}
    </div>
{% endblock %}

templates/warehouse/pages/naming.html
{% extends 'extends/index.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content_header %}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Список наименований</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'main:home_page' %}">Главная</a></li>
                        <li class="breadcrumb-item active">Список наименований</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="card card-primary card-outline">
        <div class="card-header">
            <a href="{% url 'warehouse:naming_add' %}">
                <button type="button" class="btn btn-success">Добавить </button>
            </a>
        </div>

        <div class="card-body">
            <table class="table table-bordered table-hover" style="font-size: 90%">
                <thead>
                <tr>
                    <th>ID </th>
                    <th>Название</th>
                    <th>Категория</th>
                    <th> </th>
                </tr>
                </thead>
                <tbody>

                <tr>
                    <form method="get">
                        <td>{{ form.id|add_class:"form-control" }}</td>
                        <td>{{ form.title|add_class:"form-control" }}</td>
                        <td>{{ form.category|add_class:"form-control" }}</td>
                        <td align="center">
                            <button class="btn btn-success" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </td>
                    </form>
                </tr>

                    {% for i in page_obj %}
                        <tr>
                            <td> {{ i.id }}</td>
                            <td> {{ i.title }}</td>
                            <td> {{ i.category.title }}</td>
                            <td>
                                <a href="{% url 'warehouse:naming_update' i.id %}">
                                    <i class="fa fa-edit"></i></a> &nbsp;
                                <a class="confirm-delete" href="{% url 'warehouse:naming_delete' i.id %}">
                                    <i class="fa fa-trash-alt"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    {% include 'paginator.html' %}

    </div>
{% endblock %}

templates/warehouse/pages/operations.html
{% extends base_template_name %}
{% load static %}
{% load widget_tweaks %}

{% block content_header %}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Операции в складах</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'main:home_page' %}">Главная</a></li>
                        <li class="breadcrumb-item active">Операции в складах</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="card card-primary card-outline">
        <div class="card-header">
            {% if user.role == 1 %}
                <a href="{% url 'warehouse:wh_income_add' %}">
                    <button type="button" class="btn btn-success">Приходник</button>
                </a>
            {% endif %}
            <a href="{% url 'warehouse:wh_consumption_add' %}">
                <button type="button" class="btn btn-success">Расходник</button>
            </a>
            {% if user.role == 1 %}
                <a href="{% url 'warehouse:wh_moving_add' %}">
                    <button type="button" class="btn btn-success">Перемещение</button>
                </a>
            {% endif %}
        </div>

        <div class="card-body">
            <table class="table table-bordered table-hover" style="font-size: 90%">
                <thead>
                <tr>
                    <th>id</th>
                    <th>Дата</th>
                    <th>В склад</th>
                    <th>Из склада</th>
                    <th>Тип</th>
                    <th>Менеджер</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <form method="get">
                        <td>{{ form.id|add_class:"form-control" }}</td>
                        <td>{{ form.date|add_class:"form-control" }}</td>
                        <td>{{ form.warehouse|add_class:"form-control" }}</td>
                        <td>{{ form.from_warehouse|add_class:"form-control" }}</td>
                        <td>{{ form.type|add_class:"form-control" }}</td>
                        <td>{{ form.added_by|add_class:"form-control" }}</td>
                        <td align="center">
                            <button class="btn btn-success" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </td>
                    </form>
                </tr>
                {% for i in page_obj %}
                    <tr>
                        <td>{{ i.id }}</td>
                        <td>{{ i.date }}</td>
                        <td>{{ i.warehouse }}</td>
                        <td>{% if i.from_warehouse %} {{ i.from_warehouse }} {% endif %}</td>
                        <td>{{ i.get_type_display }}</td>
                        <td>{{ i.added_by }}</td>
                        <td align="right">
                            {% if i.type == 1 %}
                                <a href="{% url 'warehouse:wh_incomeId' pk=i.id %}">
                                    <i class="fa fa-eye"></i> </a>
                                <a href="{% url 'warehouse:wh_income_cashier' pk=i.id %}">
                                    <i class="fa fa-money-bill"></i> </a>
                                <a href="{% url 'warehouse:wh_income_edit' pk=i.id %}">
                                    <i class="fa fa-edit"></i> </a>
                                <a class="confirm-delete" href="{% url 'warehouse:wh_income_delete' pk=i.id %}">
                                    <i class="fa fa-trash-alt"></i></a>
                            {% elif i.type == 2 %}

                                <a href="{% url 'warehouse:wh_consumptionId' pk=i.id %}">
                                    <i class="fa fa-eye"></i>
                                </a>
                                <a href="{% url 'warehouse:wh_consumption_edit' pk=i.id %}">
                                    <i class="fa fa-edit"></i>
                                </a>
                                <a class="confirm-delete" href="{% url 'warehouse:wh_consumption_delete' pk=i.id %}">
                                    <i class="fa fa-trash-alt"></i>
                                </a>

                            {% elif i.type == 3 %}
                                <a href="{% url 'warehouse:wh_movingId' pk=i.id %}"> <i class="fa fa-eye"></i> </a>
                                <a href="{% url 'warehouse:wh_moving_edit' pk=i.id %}">
                                    <i class="fa fa-edit"></i> </a>
                                <a class="confirm-delete" href="{% url 'warehouse:wh_moving_delete' pk=i.id %}">
                                    <i class="fa fa-trash-alt"></i>
                                </a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

    {% include 'paginator.html' %}

    </div>
{% endblock %}

templates/warehouse/pages/warehouse.html
{% extends 'extends/index.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content_header %}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Список складов</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'main:home_page' %}">Главная</a></li>
                        <li class="breadcrumb-item active">Список складов</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="card card-primary card-outline">
        <div class="card-header">
            <a href="{% url 'warehouse:warehouse_add' %}">
                <button type="button" class="btn btn-success">Добавить </button>
            </a>
        </div>

        <div class="card-body">
           <table class="table table-bordered table-hover" style="font-size: 90%">
                <thead>
                <tr>
                    <th>ID </th>
                    <th>Название</th>
                    <th>Описание</th>
                    <th> </th>
                </tr>

                <tr>
                    <form method="get">
                        <td>{{ form.id|add_class:"form-control" }}</td>
                        <td>{{ form.title|add_class:"form-control" }}</td>
                        <td>{{ form.content|add_class:"form-control" }}</td>
                        <td align="center">
                            <button class="btn btn-success" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </td>
                    </form>
                </tr>

                </thead>
                <tbody>
                    {% for i in page_obj %}
                        <tr>
                            <td> {{ i.id }}</td>
                            <td> {{ i.title }}</td>
                            <td> {{ i.content|safe }}</td>
                            <td>
                                <a href="{% url 'warehouse:warehouse_update' i.id %}">
                                    <i class="fa fa-edit"></i></a> &nbsp;
                                <a class="confirm-delete" href="{% url 'warehouse:warehouse_delete' i.id %}">
                                    <i class="fa fa-trash-alt"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>

    {% include 'paginator.html' %}

    </div>
{% endblock %}