main/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'main'

urlpatterns = [
    path('', views.HomePage.as_view(), name='home_page'),
    path('products', views.Products.as_view(), name='products'),
    path('product/edit/<int:pk>', ProductEditView.as_view(), name='product_edit'),
    path('product/delete/<int:pk>', deleteProduct, name='delete_product'),
    path('product/add/', views.ProductAddView.as_view(), name='product_add'),

    path('clients', views.ClientListView.as_view(), name='clients'),
    path('client/add/', views.ClientAddView.as_view(), name='client_add'),
    path('client/edit/<int:pk>', ClientEditView.as_view(), name='client_edit'),
    path('clients/delete/<int:pk>', delete_client, name='delete_client'),

    #path('senders', SenderListView.as_view(), name='senders'),
    path('senders/addjx/', add_sender, name='sender_add_ajax'),
    path('load_senders/', load_senders, name='load_senders_ajax'),
    path('senders/edit/<int:pk>', SenderEditView.as_view(), name='sender_edit'),
    #path('senders/delete/<int:pk>', delete_sender, name='delete_sender'),

    path('employees', EmployeeListView.as_view(), name='employees'),
    path('employee/add', EmployeeAdd.as_view(), name='employee_add'),
    path('employees/edit/<int:pk>', EmployeeEditView.as_view(), name='employee_edit'),
    path('delete/employees/<int:pk>', delete_employee, name='delete_employee'),

    path('contrageny', AgentOfClients.as_view(), name='contrageny'),
    path('contrageny/add', AgentOfClientAddView.as_view(), name='contrageny_add'),
    path('contrageny/edit/<int:pk>', AgentOfClientEditView.as_view(), name='contragenty_edit'),
    path('contrageny/delete/<int:pk>', delete_agenty, name='delete_contragenty'),

]

route/urls.py
from django.urls import path
from .views import *
from .viewRecTran import *
from .print import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'route'
urlpatterns = [
    path('list/', ListRoute.as_view(), name='list_route_url'),
    path('route/add/', CreateRoute.as_view(), name='create_route_url'),
    path('routeIDD/', showRouteModal, name='show_routeRT_url'),
    path('route/update/<int:pk>/', UpdateRouteView.as_view(), name='update_route_url'),
    path('route/delete/<int:pk>/', deleteRoute, name='delete_route_url'),

    path('routeID/<int:pk>/', ShowRouteID.as_view(), name='show_route_ID_url'),
    path('routeID_bag_report_old/<int:pk>/', RouteBagReportOld.as_view(), name='route_bag_report_old'),
    path('routeID_bag_report/<int:pk>/', RouteBagReportView.as_view(), name='route_bag_report'),
    path('routeID_num_places/<int:pk>/', RouteNumberOfPlaces.as_view(), name='route_num_places'),
    path('routeID_num_places_client/<int:pk>/', RouteNumberOfPlacesClient.as_view(), name='route_num_places_client'),
    path('routeID_num_place_agent/<int:pk>/', RouteNumberOfPlacesAgent.as_view(), name='route_num_places_agent'),
    path('routeID_count_prod/<int:pk>/', RouteCountProducts.as_view(), name='route_count_products'),

    path('routeIDprint/<int:pk>/', printRouteID, name='print_routeID_url'),
    path('routebagReportOldprint/<int:pk>/', printRouteBagReportOld, name='print_bagReport_old'),
    path('routebagReportprint/<int:pk>/', printRouteBagReport, name='print_bagReport'),
    path('routeNumberOfPlacesprint/<int:pk>/', printRouteNumberOfPlaces, name='print_number_of_places'),
    path('routeNumberOfPlacesAgentprint/<int:pk>/', printRouteNumberOfPlacesAgent, name='print_num_pl_agent'),
    path('routeProductsprint/<int:pk>/', printRouteCountProducts, name='print_products'),

    path('route_select/', selectedRoute, name='selected_route'),
    path('route_location/', change_location, name='change_location'),


    path('ReceptionTransmission/', ListReceptionTransmission.as_view(), name='list_rt'),
    path('ReceptionTransmission/history/', ListReceptionTransmissionHistory.as_view(), name='list_rt_history'),
    path('ReceptionTransmission/history/<int:pk>/', ReceptionTransmissionContractHistory, name='rt_history_id'),
    path('ReceptionTransmission/RecTransCont/<int:pk>/', ReceptionTransmissionContract, name='rt_id'),
    path('create_RecTran/', ReceptionTransmissionAddView.as_view(), name='add_rt'),
    path('ReceptionTransmission/update_RecTran/<int:pk>/', ReceptionTransmissionEditView.as_view(), name='edit_rt'),
    path('delete_RecTran/<int:pk>/', recTrans_delete, name='delete_rt'),
    path('export/<int:pk>/', export_to_pdf, name='export_pdf'),
    path('search/', searchByBagNumber, name='search_recTran_url'),
    path('search2/', SeatsAndWeightReport, name='search2_recTran_url'),

    path('reg_places', RegistrationPlaceView.as_view(), name='reg_places'),
    path('reg_places_add', RegPlacesAddView.as_view(), name='reg_places_add'),
    path('edit/reg_places/<int:pk>/', RegPlacesEditView.as_view(), name='reg_places_edit'),
    path('delete/reg_places/<int:id>/', reg_places_delete, name='reg_places_delete'),

    path('directions', DirectionsView.as_view(), name='directions'),
    path('directions_add', DirectionAddView.as_view(), name='directions_add'),
    path('edit/directions/<int:pk>', DirectionEditView.as_view(), name='directions_edit'),
    path('delete/directions/<int:id>', directions_delete, name='directions_delete'),

    path('currency', CurrencyView.as_view(), name='currency'),
    path('currency_add', CurrencyAddView.as_view(), name='currency_add'),
    path('edit/currency/<int:pk>', CurrencyEditView.as_view(), name='currency_edit'),
    path('delete/currency/<int:id>', currency_delete, name='currency_delete'),

    path('service_price', ServicePriceView.as_view(), name='service_price'),
    path('service_price/add', ServicePriceAddView.as_view(), name='service_price_add'),
    path('service_price/view/<int:pk>', ServicePriceViewID.as_view(), name='service_price_view_id'),
    path('service_price/edit/<int:pk>', ServicePriceEditView.as_view(), name='service_price_edit'),
    path('delete/service_price/<int:id>', service_price_delete, name='service_price_delete'),

    path('financial_report/', FinancialReport.as_view(), name='financial_report'),
    path('checkBagNumber/', checkBagNumber, name='check_bagNum_jx'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sapat_cargo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from sapat_cargo import settings
urlpatterns = [
    path('main/', include("main.urls")),
    path('', include("user.urls")),
    path('route/', include('route.urls')),
    path('financial/', include("financial.urls")),
    path('admin/', admin.site.urls),
    path('user/', include("user.urls",)),
    path('systems/', include("systems.urls")),
    path('debits/', include("debits.urls",)),
    path('warehouse/', include("warehouse.urls",)),
    path('chaining/', include('smart_selects.urls')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

route/models.py
from django.db import models
from xdg.Exceptions import ValidationError
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from main.models import Country, Employee, Product, Client
from datetime import datetime, date
from user.models import User

Loc = (
        ('F', 'Формируется'),
        ('O', 'Отправлен'),
        ('P', 'Прибыл'),
        ('R', 'Роздан'),)

# Валюта
class Currency(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название', unique=True,
                            error_messages={"unique": "Валюта с таким названием уже существует"})
    code = models.CharField(max_length=200, verbose_name='Код', unique=True,
                            error_messages={"unique": "Валюта с таким кодом уже существует"})
    def __str__(self):
        return self.name


# Направление
class Direction(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название')
    code = models.CharField(max_length=200, verbose_name='Код', unique=True,
                            error_messages={"unique": "Такой код направления уже существует в системе"})

    def __str__(self):
        return self.name


# Рейсы
class Route(models.Model):
    idRoute = models.IntegerField(verbose_name='ID рейса', unique=True,
                                  error_messages={"unique": "Рейс с таким ID уже существует"})
    country_recipient = models.ForeignKey(Direction, on_delete=models.CASCADE, verbose_name='Страна получатель')
    currency_Som = models.FloatField(default=0.0, verbose_name='Курс по отношению к сому')
    currency_recipient = models.ForeignKey(Currency, on_delete=models.CASCADE, null=True, verbose_name='Валюта страны получателя')
    location = models.CharField(max_length=1, choices=Loc, default=Loc[0][0], verbose_name='Местоположение')
    date = models.DateTimeField(default=datetime.now, blank=True, verbose_name='Дата') #default=datetime.datetime.now
    status = models.BooleanField(default=False, verbose_name='Статус')
    control_status = models.BooleanField(default=False, verbose_name='Контрольный статус')
    status_places = models.BooleanField(default=False, verbose_name='Статус количества мест')
    note = models.TextField(default="", verbose_name='Примечание', null=True, blank=True)

    def __str__(self):
        return str(str(self.idRoute)+' ('+self.country_recipient.name+')')

class Loader(models.Model):
    name = models.ForeignKey(Employee, on_delete=models.CASCADE)
    route = models.ForeignKey(Route, on_delete=models.CASCADE)

# Оформление
class Registration(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название', unique=True,
                            error_messages={"unique": "Такое место уже существует"})
    description = models.TextField(verbose_name='Описание', null=True, blank=True)

    def __str__(self):
        return self.name
SerV = (
        ('0', 'За вес (кг)'),
        ('1', 'Погрузка'),
        ('2', 'Доотправка'),
        ('3', 'Большой мешок'),
        ('4', 'Средний мешок'),
        ('5', 'Маленький мешок'),
        ('6', 'Разгузка'),
        ('7', 'Свой мешок'),
    )

# Цены сервисов
class ServicePrice(models.Model):
    date = models.DateTimeField(default=datetime.now, blank=True, verbose_name="Дата")

    def __str__(self):
        return self.id.__str__()

# Цены
class Price(models.Model):
    service = models.CharField(max_length=1, choices=SerV, default=SerV[0][0], verbose_name="Сервис")
    country = models.ForeignKey(Direction, on_delete=models.CASCADE, verbose_name="Страна")
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE, verbose_name="Валюта")
    price = models.FloatField(default=0.0, verbose_name="Цена")
    servicePrice = models.ForeignKey(ServicePrice, on_delete=models.CASCADE)

# Прием/передача
class ReceptionTransmission(models.Model):
    route = models.ForeignKey(Route, on_delete=models.CASCADE, verbose_name='ID рейса')
    sender = models.ForeignKey(Client, on_delete=models.PROTECT, related_name='sender1', verbose_name='Грузоотправитель')
    recipient = models.ForeignKey(Client, on_delete=models.PROTECT, related_name='recipient', verbose_name='Грузополучатель')
    registration = models.ForeignKey(Registration, on_delete=models.CASCADE, verbose_name='Место оформления')
    operator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='operators')
    #status = models.BooleanField()
    dateRT = models.DateTimeField(default=datetime.now, verbose_name='Дата')
    history = models.BooleanField(default=False)
    paid = models.FloatField(default=0.0)
    remainder = models.FloatField(default=0.0)
    pogr = models.IntegerField(default=0)

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return self.id.__str__()

# Услуги
class Services(models.Model):
    service = models.CharField(max_length=1, choices=SerV, default=SerV[0][0])
    count = models.IntegerField(default=0)
    priceIV = models.FloatField(default=0.0)
    status = models.BooleanField()
    id_REC_TRAN = models.ForeignKey(ReceptionTransmission, on_delete=models.CASCADE)

# Досмотрщик
class Inspector(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, verbose_name='досмотрщик')
    id_REC_TRAN = models.ForeignKey(ReceptionTransmission, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('employee', 'id_REC_TRAN',)

    def __str__(self):
        return self.employee.fullname

# Упаковщик
class Packer(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, verbose_name='упаковщик')
    id_REC_TRAN = models.ForeignKey(ReceptionTransmission, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('employee', 'id_REC_TRAN',)


def validate_even(value):
    if value == 0:
        raise ValidationError(
            _('Должно быть больше 0'),
            params={'value': value},
        )
# Список Товаров
class ProductP(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    bag_number = models.PositiveIntegerField(default=0, validators=[validate_even])
    weight = models.FloatField(default=0.0)
    count = models.IntegerField(default=0, validators=[validate_even])
    recTranID = models.ForeignKey(ReceptionTransmission, on_delete=models.CASCADE)
    def __str__(self):
        return self.product.name

class NumberOfPlaces(models.Model):
    recipient = models.ForeignKey(Client, on_delete=models.CASCADE)
    agent = models.ForeignKey("debits.ClientContrAgents", on_delete=models.CASCADE)
    unloading = models.FloatField(default=0.0)
    route = models.ForeignKey(Route, on_delete=models.CASCADE)

templates/route/pages/route_bag_report.html
{% extends base_template_name %}
{% block css %}
    {% load static %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="{% static "js/route/show_route_ID.js" %}"></script>
{% endblock %}

{% block content_header %}

    <div class="content-header">
        <div class="container-fluid">

            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Просмотр Сумок Рейса</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'main:home_page' %}">Главная</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'route:list_route_url' %}">Рейсы</a></li>
                        <li class="breadcrumb-item active">Просмотр Сумок Рейса</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block content %}

    <div class="card card-primary card-outline">
        <div class="card-body">

        <div class="btn-group">
                <a class="btn btn-success print" href="{% url 'route:print_bagReport' pk=routeID %}"><i class="fa fa-fw fa-print"></i> Печать</a>
                <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <span class="caret"></span>
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a class="dropdown-item" href="{% url 'route:route_bag_report_old' routeID %}"><i class="fa fa-eye"></i> Отчет по сумкам (старый)</a></li>
                    <li><a class="dropdown-item" href="{% url 'route:route_bag_report' routeID %}"><i class="fa fa-eye"></i> Отчет по сумкам </a></li>
                    <li><a class="dropdown-item"
                           {% if user.role == 1 or user.role == 5%}
                           href="{% url 'route:route_num_places' routeID %}"
                            {% elif user.role == 6 %}
                           href="{% url 'route:route_num_places_client' routeID %}"
                            {% endif %}
                    ><i class="fa fa-eye"></i> Количество мест </a></li>
                    <li><a class="dropdown-item" href="{% url 'route:route_num_places_agent' routeID %}"><i class="fa fa-eye"></i> Количество мест (По контрагентам)</a></li>
                    <li><a class="dropdown-item" href="{% url 'route:route_count_products' routeID %}"><i class="fa fa-eye"></i> Количество товара </a></li>
                </ul>
            </div>

            <br>
            <h5 style="text-align: center"> {{ routeInf }} </h5>
            <br>
            <table width="100%" border="1">
                <thead>
                <tr>
                    <th>Код</th>
                    <th>Номера мешков</th>
                    <th>Кол-во</th>
                    <th>Вес</th>
                </tr>
                </thead>
                <tbody>
                {% for k,v in dict.items %}
                    <tr>
                        <td>{{ k }}</td>
                        <td>{{ v.0 }}</td>
                        <td>{{ v.2 }}</td>
                        <td>{{ v.1 }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <BR><p><b>Итого: {{ remainder }}</b><BR><b>Итого вес: {{ weight_sum }}</b></p>

        </div>
    </div>

{% endblock %}

templates/route/pages/route_bagreport_old.html
{% extends base_template_name %}
{% block css %}
    {% load static %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="{% static "js/route/show_route_ID.js" %}"></script>
{% endblock %}

{% block content_header %}

    <div class="content-header">
        <div class="container-fluid">

            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Просмотр Сумок Рейса</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'main:home_page' %}">Главная</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'route:list_route_url' %}">Рейсы</a></li>
                        <li class="breadcrumb-item active">Просмотр Сумок Рейса</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block content %}

    <div class="card card-primary card-outline">

        <div class="card-body">
           <div class="btn-group">
                <a class="btn btn-success print" href="{% url 'route:print_bagReport_old' pk=routeID %}"><i class="fa fa-fw fa-print"></i> Печать</a>
                <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <span class="caret"></span>
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a class="dropdown-item" href="{% url 'route:route_bag_report_old' routeID %}"><i class="fa fa-eye"></i> Отчет по сумкам (старый)</a></li>
                    <li><a class="dropdown-item" href="{% url 'route:route_bag_report' routeID %}"><i class="fa fa-eye"></i> Отчет по сумкам </a></li>
                    <li><a class="dropdown-item"
                           {% if user.role == 1 or user.role == 5%}
                           href="{% url 'route:route_num_places' routeID %}"
                            {% elif user.role == 6 %}
                           href="{% url 'route:route_num_places_client' routeID %}"
                            {% endif %}
                    ><i class="fa fa-eye"></i> Количество мест </a></li>
                    <li><a class="dropdown-item" href="{% url 'route:route_num_places_agent' routeID %}"><i class="fa fa-eye"></i> Количество мест (По контрагентам)</a></li>
                    <li><a class="dropdown-item" href="{% url 'route:route_count_products' routeID %}"><i class="fa fa-eye"></i> Количество товара </a></li>
                </ul>
            </div>
            <br>
            <h5 style="text-align: center"> {{ routeInf }} </h5>
            <br>
            <table border="1">
                <thead>
                <tr>
                    {% for k in list.0 %}
                        <th style="height: 40px;">№ сумки</th>
                    {% endfor %}
                </tr>
                </thead>
                <tbody>
                {% for dict in list %}
                    <tr>
                        {% for k,v in dict.items %}
                            <td valign="top">{{ k }}<b>({{ v.0 }})</b>
                                <br>{{ v.1 }}<hr> </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

templates/route/pages/route_num_places_agent.html
{% extends base_template_name %}
{% load static %}
{% load formset_tags %}
{% load widget_tweaks %}
{% block css %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="{% static "js/route/show_route_ID.js" %}"></script>
{% endblock %}

{% block content_header %}

    <div class="content-header">
        <div class="container-fluid">

            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Просмотр Количества места</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'main:home_page' %}">Главная</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'route:list_route_url' %}">Рейсы</a></li>
                        <li class="breadcrumb-item active">Просмотр Количества мест</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="card card-primary card-outline">
        <div class="card-body">
            <div class="btn-group">
                <a class="btn btn-success print" href="{% url 'route:print_num_pl_agent' pk=routeID %}"><i class="fa fa-fw fa-print"></i> Печать</a>
                <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <span class="caret"></span>
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a class="dropdown-item" href="{% url 'route:route_bag_report_old' routeID %}"><i class="fa fa-eye"></i> Отчет по сумкам (старый)</a></li>
                    <li><a class="dropdown-item" href="{% url 'route:route_bag_report' routeID %}"><i class="fa fa-eye"></i> Отчет по сумкам </a></li>
                    <li><a class="dropdown-item"
                            {% if user.role == 1 or user.role == 5%}
                           href="{% url 'route:route_num_places' routeID %}"
                            {% elif user.role == 6 %}
                           href="{% url 'route:route_num_places_client' routeID %}"
                            {% endif %}
                    ><i class="fa fa-eye"></i> Количество мест </a></li>
                    <li><a class="dropdown-item" href="{% url 'route:route_num_places_agent' routeID %}"><i class="fa fa-eye"></i> Количество мест (По контрагентам)</a></li>
                    <li><a class="dropdown-item" href="{% url 'route:route_count_products' routeID %}"><i class="fa fa-eye"></i> Количество товара </a></li>
                </ul>
            </div>
            <br>
            <h5 style="text-align: center"> {{ routeInf }} </h5>
            <br>

            <table border="1" width="100%" style="font-size: 95%">
                <thead style="text-align: center">
                <th>№</th>
                <th>Код</th>
                <th>Получатель</th>
                <th>рынок</th>
                <th>контейнер</th>
                <th>ряд</th>
                <th>Места</th>
                <th>Вес</th>
                <th>Сумма</th>
                </thead>
                <tbody>
                {% for f1 in Ret %}
                    {% for k,val1 in f1.items %}
                        <tr>
                            <td colspan="9" align="center"><b>{{ k }}</b></td>
                        </tr>
                        {% for val2 in val1 %}
                            <tr align="center">
                                {% for v in val2 %}
                                    <td>
                                        {% if v %} {{ v }} {% endif %}
                                    </td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    {% endfor %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/route/pages/route_products.html
{% extends base_template_name %}
{% block css %}
    {% load static %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="{% static "js/route/show_route_ID.js" %}"></script>
{% endblock %}

{% block content_header %}

    <div class="content-header">
        <div class="container-fluid">

            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Просмотр Количества товара</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'main:home_page' %}">Главная</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'route:list_route_url' %}">Рейсы</a></li>
                        <li class="breadcrumb-item active">Просмотр Количества товара</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block content %}

    <div class="card card-primary card-outline">
        <div class="card-body">
            <div class="btn-group">
                <a class="btn btn-success print" href="{% url 'route:print_products' pk=routeID %}"><i class="fa fa-fw fa-print"></i> Печать</a>
                <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <span class="caret"></span>
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a class="dropdown-item" href="{% url 'route:route_bag_report_old' routeID %}"><i class="fa fa-eye"></i> Отчет по сумкам (старый)</a></li>
                    <li><a class="dropdown-item" href="{% url 'route:route_bag_report' routeID %}"><i class="fa fa-eye"></i> Отчет по сумкам </a></li>
                    <li><a class="dropdown-item"
                           {% if user.role == 1 or user.role == 5%}
                           href="{% url 'route:route_num_places' routeID %}"
                            {% elif user.role == 6 %}
                           href="{% url 'route:route_num_places_client' routeID %}"
                            {% endif %}
                    ><i class="fa fa-eye"></i> Количество мест </a></li>
                    <li><a class="dropdown-item" href="{% url 'route:route_num_places_agent' routeID %}"><i class="fa fa-eye"></i> Количество мест (По контрагентам)</a></li>
                    <li><a class="dropdown-item" href="{% url 'route:route_count_products' routeID %}"><i class="fa fa-eye"></i> Количество товара </a></li>
                </ul>
            </div>
            <br>
            <h5 style="text-align: center"> {{ routeInf }} </h5>
            <br>
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>№</th>
                    <th>Наименование товара</th>
                    <th>Код ТНВД</th>
                    <th>Количество</th>
                    <th>Вес</th>
                    <th>Сумки</th>
                </tr>
                </thead>
                <tbody>
                {% for k,v in dict.items %}
                    <tr>
                        {% for i in v %}
                            <td>{{ i }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
                <tr>
                    {% for l in last %}
                        <td><b>{{ l }}</b></td>
                    {% endfor %}
                </tr>
                </tbody>
            </table>
            <BR><p><b></b><BR><b>Итого вес: {{ weight_sum }}</b></p>

        </div>
    </div>

{% endblock %}